# Generated by Django 3.2.4 on 2021-07-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='vacunas_fabricadas',
            field=models.IntegerField(default=0),
        ),
    ]
