# Generated by Django 3.2.4 on 2021-07-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard_vacunas_fabricadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='last_upgrade',
            field=models.CharField(max_length=200),
        ),
    ]
