# Generated by Django 3.2.4 on 2021-06-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OC', '0002_auto_20210619_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='anulacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='fechaEntrega',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='notas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='rechazo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
