# Generated by Django 3.2.5 on 2021-07-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OC', '0003_auto_20210620_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
    ]
