# Generated by Django 3.2.5 on 2021-07-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OC', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField()),
                ('tick', models.IntegerField()),
            ],
        ),
    ]
