# Generated by Django 3.2.5 on 2021-07-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OC', '0005_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contador',
            name='tick',
            field=models.IntegerField(default=0),
        ),
    ]
