# Generated by Django 3.2.5 on 2021-07-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OC', '0005_ordendecompra_en_produccion'),
        ('OC', '0006_alter_contador_tick'),
    ]

    operations = [
    ]
